version: "3.8"

services:

  amqp:
    image: rabbitmq:3.12.10
    restart: always
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 10
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

    ports:
      - "15672:15672"
      - "5672:5672"

  bot:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    command: bash -c "python bot.py"
    depends_on:
      amqp:
        condition: service_healthy

  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    command: bash -c "python server.py"
    depends_on:
      amqp:
        condition: service_healthy
    ports:
      - "8888:8888"